server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:root}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/admin

persons:
  base-url: ${PERSONS_URL:http://localhost:8080/persons}
  by-cpf: ${BY_CPF:/cpf/{cpf}}